ifndef::imagesdir[:imagesdir: ../images]

[[section-introduction-and-goals]]
== Introducción y Ojetivos (wiq_es04c)

El proyecto de wiq_es04c es un proyecto desarrollado en la asignatura  Arquitectura del Software. Consiste en la creacion de una aplicacion web al estilo "Saber y Ganar". Es decir, es un juego de preguntas de cultura general.

Los desarrolladores de la aplicacion son por David Álvarez Díaz, Zohaib Akhtar Kausar, Sara Lamuño García, Yago Navajas González y Santiago López Laso.

La aplicación tendra su base para las preguntas y las respuestas en Wikidata , la base de conocimiento editada en colaboracion.


=== Requisitos Funcionales

****
* Los usuarios se deberan loggear en la página, esto servirá para tener registro de unas serie de parámetros, como puede ser las veces que se ha jugado. 
* Se podrán responder preguntas autogeneradas y ver si han acertado fallado, así como la respuesta correcta.
* Las preguntas deberán ser respondidas en un tiempo límite.
* Las preguntas seguirán la misma estructura: 1 pregunta correcta y 3 incorrectas, generadas automáticamente.
* Los usuarios podrán consultar datos sobre su cuentas, como pueden ser las veces que han jugado o el número de preguntas que han acertado o fallado. 


****

=== Atributos de Calidad

[options="header",cols="1,2,2"]
|===
| Prioridad | Objetivo | Descripción
| 1 | Usabilidad | Todos los usuarios deben poder usar la aplicación sin tener en cuenta sus limitaciones.
| 2 | Privacidad |  Los datos sensibles de los usuarios deben estar restringidos al mismo usuario.
| 3 | Mantenibilidad | El código y documentación de la aplicación ha de estar conformado de tal forma que sea factible hacer cambios y ampliaciones en la aplicación.
| 4 | Eficiciencia | Los tiempos entre operaciones han de ser asumibles.
| 5 | Fiabilidad | Los datos usados en la aplicación deben ser los correctos.
|===


=== Stakeholders

[options="header",cols="1,2,2"]
|===
|Role/Name|Contact|Expectations
| Equipo de Desarrollo | Yago Navajas Gonzalez -> UO287746@uniovi.es +
David Álvarez Díaz -> UO283196@uniovi.es +
Zohaib Akhtar Kausar -> UO291060@uniovi.es +
Sara Lamuño García -> UO283706@uniovi.es +
Santiago Lopez Laso -> UO277369@uniovi.es | Los estudiantes que llevarán a cabo el desarrollo de la aplicación. Serán los encargados de la arquitectura, la documentación y la codificación.
| Profesores | Jose Emilio Labra Gayo | Supervisores de los avances y encargados de evaluar la aplicacion final y el desarrollo de la misma.
| Usuario | Jugador de la aplicación | Personas que puedan interactuar tanto con el registro de usuarios como con el juego en sí y pueda completar correctamente una partida.
|===
