ifndef::imagesdir[:imagesdir: ../images]

[[section-solution-strategy]]
== Solution Strategy


[role="arc42help"]
****
.Contents
A short summary and explanation of the fundamental decisions and solution strategies, that shape system architecture. It includes

* technology decisions
* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture. They are the foundation for many other detailed decisions or implementation rules.

.Form
Keep the explanations of such key decisions short.

Motivate what was decided and why it was decided that way,
based upon problem statement, quality goals and key constraints.
Refer to details in the following sections.
****

****
Decisiones tecnológicas

Hemos decidido realizar la parte de Front-End con React y la parte de Back-End con la estructura de los microservicios. 
El despliegue se realizará a través de una máquina virtual de Azure, con ayuda de Docker y GitHub Actions.

[options="header",cols="1,2"]
|===
|Aplicación
|Breve explicación
|React
|Biblioteca de JavaScript que nos servirá para realizar las interfaces de usuario necesarias para el Front-End.
|Microservicios
|Aquí es donde se unirá el uso de la API (Application Programming Interface) de WikiData, la cual nos sacará los datos para las preguntas y las respuestas
de la aplicación con el proyecto en sí.
|Azure
|Plataforma para la creación de la máquina virtual que servirá para desplegar la aplicación.
|Docker
|Encargado de dividir el contenido del proyecto en diversos contenedores (en nuestro caso 4) y sea más fácil de manipular el contenido de dicho proyecto.
|GitHub Actions
|Nos servirá para el despliegue del proyecto, pero de forma automática en vez de desplegarlo todo a mano. Cabe a destacar que también están implementados
unos test para asegurar el correcto despliegue del proyecto.
|===

Decisiones de cómo llegar a las metas principales (En desarrollo):
[options="header",cols="1,2"]
|===
|Usabilidad
|
|Privacidad
|
|Mantenibilidad
|
|Eficiciencia
|
|Fiabilidad
|

|===



Decisiones organizativas

En la primera semana nos hemos dividido en dos equipos con el objetivo de tocar todas las partes del proyecto. La estructura de los equipos es la siguiente:

----
-> Equipo documentación
     Sara Lamuño García -> UO283706@uniovi.es 
     Yago Navajas Gonzalez -> UO287746@uniovi.es
-> Equipo desarrollo del proyecto
     David Álvarez Díaz -> UO283196@uniovi.es
     Zohaib Akhtar Kausar -> UO291060@uniovi.es
     Santiago Lopez Laso -> UO277369@uniovi.es
----

La realización de las actas de las reuniones diarias se le ha asignado la tarea a Sara Lamuño García.

En las siguientes semanas habrá rotación o cambio de miembros en ambos equipos.

En la segunda semana hemos decidido ponernos de manera más profunda con la documentación, asignando diferentes apartados de esta a cada miembro del equipo:

[options="header",cols="1,2"]
|===
| Miembro
| Documentación
| Sara Lamuño García
| 4, 6, 12
| Yago Navajas Gonzalez
| 1, 8, 9
| David Álvarez Díaz
| 5, 7
| Zohaib Akhtar Kausar
| 10, 11
| Santiago Lopez Laso
| 2, 3
|===

Se han creado el mismo número de Issues como apartados de la documentación hay para asignarla a cada miembro.

En cuanto al despliegue de la aplicación se van a arreglar los errores que salen en los test al intentar desplegarla, ya que se han cambiado
algunos valores predefinidos, por lo que los test también predefinidos fallarán.

.Further Information

See https://docs.arc42.org/section-4/[Solution Strategy] in the arc42 documentation.

****
