ifndef::imagesdir[:imagesdir: ../images]

[[section-solution-strategy]]
== Solution Strategy


[role="arc42help"]
****
.Contents
A short summary and explanation of the fundamental decisions and solution strategies, that shape system architecture. It includes

* technology decisions
* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture. They are the foundation for many other detailed decisions or implementation rules.

.Form
Keep the explanations of such key decisions short.

Motivate what was decided and why it was decided that way,
based upon problem statement, quality goals and key constraints.
Refer to details in the following sections.


Decisiones organizativas

En la primera semana nos hemos dividido en dos equipos con el objetivo de tocar todas las partes del proyecto. La estructura de los equipos es la siguiente:

----
-> Equipo documentación
     Sara Lamuño García -> UO283706@uniovi.es 
     Yago Navajas Gonzalez -> UO287746@uniovi.es
-> Equipo desarrollo del proyecto
     David Álvarez Díaz -> UO283196@uniovi.es
     Zohaib Akhtar Kausar -> UO291060@uniovi.es
     Santiago Lopez Laso -> UO277369@uniovi.es
----

La realización de las actas de las reuniones diarias se le ha asignado la tarea a Sara Lamuño García.

En las siguientes semanas habrá rotación o cambio de miembros en ambos equipos.

.Further Information

See https://docs.arc42.org/section-4/[Solution Strategy] in the arc42 documentation.

****
