ifndef::imagesdir[:imagesdir: ../images]

[[section-solution-strategy]]
== Estrategia de Soluci칩n 游닄

=== Decisiones tecnol칩gicas 游눹

Hemos decidido realizar la parte de Front-End con React y la parte de Back-End con la estructura de los microservicios. 
El despliegue se realizar치 a trav칠s de una m치quina virtual de Azure, con ayuda de Docker y GitHub Actions.

[options="header",cols="1,2"]
|===
|Aplicaci칩n
|Breve explicaci칩n
|React
|Biblioteca de JavaScript que nos servir치 para realizar las interfaces de usuario necesarias para el Front-End.
|Microservicios
|Aqu칤 es donde se unir치 el uso de la API (Application Programming Interface) de WikiData, la cual nos sacar치 los datos para las preguntas y las respuestas
de la aplicaci칩n con el proyecto en s칤.
|Azure
|Plataforma para la creaci칩n de la m치quina virtual que servir치 para desplegar la aplicaci칩n.
|Docker
|Encargado de dividir el contenido del proyecto en diversos contenedores (en nuestro caso 4) y sea m치s f치cil de manipular el contenido de dicho proyecto.
|GitHub Actions
|Nos servir치 para el despliegue del proyecto, pero de forma autom치tica en vez de desplegarlo todo a mano. Cabe a destacar que tambi칠n est치n implementados
unos test para asegurar el correcto despliegue del proyecto.
|===

Decisiones de c칩mo llegar a las metas principales (En desarrollo):
[options="header",cols="1,2"]
|===
| Decision | Como llegar
| Usabilidad | La aplicacion seguira los principios basicos de usabilidad y estos seran testeados en diferentes escenarios.
| Mantenibilidad | El sistema sera mantenible gracias a la mantenibilidad de sus subsistemas. 
| Eficiciencia | Para que la aplicacion sea rapida se usaran la base de datos y no se tendran que generar datos en caliente que pueden perjudicar a los tiempo de carga.
| Fiabilidad | Todos los datos mostrados seran correctos y para esta comprobacion se usara la base de datos de Wikidata y sus entidades e ID's asociados. 
| Privacidad | Los datos de los usuarios seran privados y no seran accesibles a ningun usuario. 

|===



=== Decisiones organizativas 游논

En la primera semana nos hemos dividido en dos equipos con el objetivo de tocar todas las partes del proyecto. La estructura de los equipos es la siguiente:

[options="header",cols="1,2"]
|===
|Equipo
|Miembros
|Equipo documentaci칩n
|     Sara Lamu침o Garc칤a -> UO283706@uniovi.es 
     Yago Navajas Gonzalez -> UO287746@uniovi.es
|Equipo desarrollo del proyecto
|     David 츼lvarez D칤az -> UO283196@uniovi.es
     Zohaib Akhtar Kausar -> UO291060@uniovi.es
     Santiago Lopez Laso -> UO277369@uniovi.es
|===

La realizaci칩n de las actas de las reuniones diarias se le ha asignado la tarea a Sara Lamu침o Garc칤a.

En las siguientes semanas habr치 rotaci칩n o cambio de miembros en ambos equipos.

En la segunda semana hemos decidido ponernos de manera m치s profunda con la documentaci칩n, asignando diferentes apartados de esta a cada miembro del equipo:

[options="header",cols="1,2"]
|===
| Miembro
| Documentaci칩n
| Sara Lamu침o Garc칤a
| 4, 6, 12
| Yago Navajas Gonzalez
| 1, 8, 9
| David 츼lvarez D칤az
| 5, 7
| Zohaib Akhtar Kausar
| 10, 11
| Santiago Lopez Laso
| 2, 3
|===

Se han creado el mismo n칰mero de Issues como apartados de la documentaci칩n hay para asignarla a cada miembro.

En cuanto al despliegue de la aplicaci칩n se van a arreglar los errores que salen en los test al intentar desplegarla, ya que se han cambiado
algunos valores predefinidos, por lo que los test tambi칠n predefinidos fallar치n.
