ifndef::imagesdir[:imagesdir: ../images]

[[section-deployment-view]]


== Vista de Despliegue 


=== Infrastructure Level 1 锔

EN DESARROLLO.

_**<Overview Diagram>**_ 

EN DESARROLLO.

Motivation ぉ:: 

1. Disponibilidad: Se busca una aplicaci贸n que sea capaz de prestar servicio de manera continuada, con resistencia a fallos.
2. Eficiencia: Se busca una aplicaci贸n que ofreza un rendimiento 贸ptimo para la generaci贸n de preguntas desde dispositivos con pocas capacidades.
3. Cumplimiento de Requisitos Regulatorios: El uso de Wikidata como fuente de datos en nuestra aplicaci贸n est谩 respaldado por la necesidad de cumplir con requisitos regulatorios y normativos espec铆ficos. Esta elecci贸n se basa en las siguientes consideraciones:



Quality and/or Performance Features :: 

1.Rendimiento: Se busca que la aplicaci贸n tenga un rendimiento 贸ptimo en dispositivos m贸viles y tablets.
2.Adaptabilidad: La aplicaci贸n tiene que ser adaptable en diferentes dispositivos para as铆 poder garantizar su uso.




EN DESARROLLO.

Mapping of Building Blocks to Infrastructure :: 

EN DESARROLLO.


=== Infrastructure Level 2 锔

EN DESARROLLO.


==== _<Infrastructure Element 1>_

EN DESARROLLO.
