ifndef::imagesdir[:imagesdir: ../images]

[[section-deployment-view]]


== Deployment View 


=== Infrastructure Level 1 锔

EN DESARROLLO.

[role="arc42help"]
****
Describe (usually in a combination of diagrams, tables, and text):

* distribution of a system to multiple locations, environments, computers, processors, .., as well as physical connections between them
* important justifications or motivations for this deployment structure
* quality and/or performance features of this infrastructure
* mapping of software artifacts to elements of this infrastructure

For multiple environments or alternative deployments please copy and adapt this section of arc42 for all relevant environments.
****

_**<Overview Diagram>**_ 

EN DESARROLLO.

Motivation:: ぉ

1. Disponibilidad: Se busca una aplicaci贸n que sea capaz de prestar servicio de manera continuada, con resistencia a fallos.
2. Eficiencia: Se busca una aplicaci贸n que ofreza un rendimiento 贸ptimo para la generaci贸n de preguntas desde dispositivos con pocas capacidades.
3. Cumplimiento de Requisitos Regulatorios: El uso de Wikidata como fuente de datos en nuestra aplicaci贸n est谩 respaldado por la necesidad de cumplir con requisitos regulatorios y normativos espec铆ficos. Esta elecci贸n se basa en las siguientes consideraciones:



Quality and/or Performance Features:: 

1.Rendimiento: Se busca que la aplicaci贸n tenga un rendimiento 贸ptimo en dispositivos m贸viles y tablets.
2.Adaptabilidad: La aplicaci贸n tiene que ser adaptable en diferentes dispositivos para as铆 poder garantizar su uso.




EN DESARROLLO.

Mapping of Building Blocks to Infrastructure:: 

EN DESARROLLO.
_<description of the mapping>_


=== Infrastructure Level 2 锔

[role="arc42help"]
****
Here you can include the internal structure of (some) infrastructure elements from level 1.

Please copy the structure from level 1 for each selected element.
****

EN DESARROLLO.


==== _<Infrastructure Element 1>_

_<diagram + explanation>_

==== _<Infrastructure Element 2>_

_<diagram + explanation>_

...

==== _<Infrastructure Element n>_

_<diagram + explanation>_
